name: (Develop) Synchronize to forked repo
on:
  push:
    branches:
      - develop

jobs:
  sync:
    name: Sync forked repo
    runs-on: ubuntu-latest

    steps:
      - name: Checkout develop
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.DEV_AUTO_SYNC_TOKEN }}
          fetch-depth: 0
          ref: develop

      - name: Add remote-url
        run: |
          git remote add forked-repo https://hyeonjin6530:${{ secrets.DEV_AUTO_SYNC_TOKEN }}@github.com/hyeonjin6530/billilge-frontend
          git config user.name hyeonjin6530
          git config user.email ${{ secrets.DEV_EMAIL }}

      - name: Push changes to forked-repo
        run: |
          git push -f forked-repo develop

      - name: Clean up
        run: |
          git remote remove forked-repo
